CREATE DATABASE 'mystudentdb';
CREATE TABLE 'student' (id INT(100) NOT NULL AUTO_INCREMENT PRIMARY KEY, uuid VARCHAR(100) NOT NULL, firstname VARCHAR(100) NOT NULL, lastname VARCHAR(100) NOT NULL, phone VARCHAR(100) NOT NULL, email VARCHAR(100) NOT NULL);
